# Usar imagem node para build
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . ./
RUN npm run build

# Imagem final leve com nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

# Expõe a porta 80 padrão do nginx
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
