version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: chatbot_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ChatBotDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chatbot-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=ChatBotDb;Username=postgres;Password=123456
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - chatbot-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      # Para acessar o backend dentro da rede Docker
      - VITE_API_BASE_URL=http://backend:8080
    ports:
      - "5173:80"
    networks:
      - chatbot-network

volumes:
  pgdata:

networks:
  chatbot-network:
    driver: bridge